import android.os.Bundle
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import androidx.fragment.app.Fragment
import androidx.recyclerview.widget.LinearLayoutManager
import androidx.recyclerview.widget.RecyclerView
import com.example.cpen321app.MainActivity
import com.example.cpen321app.R
import com.example.cpen321app.Task
import com.example.cpen321app.TaskAdapter

// Generated by Copilot
class TaskListFragment : Fragment() {

    private lateinit var recyclerView: RecyclerView
    private lateinit var taskAdapter: TaskAdapter

    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
        // Inflate the layout for this fragment
        val view = inflater.inflate(R.layout.fragment_task_list, container, false)

        // Initialize RecyclerView
        recyclerView = view.findViewById(R.id.recyclerView)
        recyclerView.layoutManager = LinearLayoutManager(activity)

        // Assuming you have acquired the tasks from the backend
        val tasks = listOf(
            Task("Task 1"),
            Task("Task 2"),
            Task("Task 3")
        )

        taskAdapter = TaskAdapter(tasks)
        recyclerView.adapter = taskAdapter

        return view
    }
}