package com.example.cpen321app

import android.content.Context
import androidx.security.crypto.EncryptedSharedPreferences
import androidx.security.crypto.MasterKey

// Generated by copilot

class SecurePreferences(context: Context) {

    private val masterKeyAlias = MasterKey.Builder(context)
        .setKeyScheme(MasterKey.KeyScheme.AES256_GCM)
        .build()

    private val sharedPreferences = EncryptedSharedPreferences.create(
        context,
        "secure_prefs_file",
        masterKeyAlias,
        EncryptedSharedPreferences.PrefKeyEncryptionScheme.AES256_SIV,
        EncryptedSharedPreferences.PrefValueEncryptionScheme.AES256_GCM
    )

    // save a value
    fun saveSecureValue(key: String, value: String) {
        sharedPreferences.edit().putString(key, value).apply()
    }

    // retrieve a value
    fun getSecureValue(key: String): String? {
        return sharedPreferences.getString(key, null)
    }
}
